### PR TITLE
Series of different improvements and bug fixes

### LINKED ISSUE #1: Frontend crash in get_rest_url
Original issue: https://github.com/humanmade/Mercator/issues/86

> After installing Mercator, the frontend of one of my sites (haven't checkt the others) crashes with the following stack trace:
>
> `Fatal error:  Uncaught Error: Call to a member function using_index_permalinks() on null in /path/wordpressmu/wp-includes/rest-api.php:314
> Stack trace:
> ```
> #0 /path/wordpressmu/wp-includes/rest-api.php(363): get_rest_url(NULL, '/', 'json')
> #1 /path/wordpressmu/wp-content/mu-plugins/mercator-redirect/redirect.php(64): rest_url()
> #2 /path/wordpressmu/wp-includes/class-wp-hook.php(298): Mercator\Redirect\handle_redirect('')
> #3 /path/wordpressmu/wp-includes/class-wp-hook.php(323): WP_Hook->apply_filters(NULL, Array)
> #4 /path/wordpressmu/wp-includes/plugin.php(453): WP_Hook->do_action(Array)
> #5 /path/wordpressmu/wp-settings.php(326): do_action('plugins_loaded')
> #6 /path/wordpressmu/wp-config.php(226): require_once('/www/vhosts/wor...')
> #7 /path/wordpressmu/wp-load.php(37): require_once('/www/vhosts/wor...')
> #8 /path/wordpressmu/wp-blog-header.php(13): require_once('/www/vhosts/wor...')
> #9 /path/wordpressmu/index.php(17): require('/www/vhosts/wor...')
> #10 {main}
>  thr in /path/wordpressmu/wp-includes/rest-api.php on line 314`
> ```
>
> It looks like `global $wp_rewrite;` is null at that point.

### PR DESCRIPTION
**Pull request by spacedmonkey**
This commit includes the following improvements. 

- Bug fix for fatal error of rest api. 
- Add new filter `mercator.redirect.status.code`
- Check if redirected domain is the same as current domain. This stops redirect loops
- Use set_url_scheme, so make sure redirect to the same scheme as current site, ie https. 

Fixes #1

### CODE REVIEW

File: redirect.php [hunk 1]
```diff
@@ -60,8 +60,9 @@ function handle_redirect() {
 		return;
 	}
 
+
 	// Don't redirect REST API requests
-	if ( 0 === strpos( $_SERVER['REQUEST_URI'], parse_url( rest_url(), PHP_URL_PATH ) ) ) {
+	if ( defined('REST_REQUEST') && REST_REQUEST ) {
```
Comment (roborourke) [inline redirect.php]: Coding standards - spaces inside round brackets

File: redirect.php [hunk 2]
```diff
@@ -81,8 +82,14 @@ function handle_redirect() {
...
 
+	// If current domain and domain mapping are the same, exit early.
+	$domain = $mapping->get_site()->domain;
+	if ( $domain == $_SERVER['HTTP_HOST'] ) {
+		return;
+	}
+
 	// Use blogs table domain as the primary domain
-	wp_redirect( 'http://' . $mapping->get_site()->domain . esc_url_raw( $_SERVER['REQUEST_URI'] ), 301 );
+	wp_redirect( set_url_scheme( "http://" . $domain . esc_url_raw( $_SERVER['REQUEST_URI'] ) ), apply_filters( 'mercator.redirect.status.code', 301 ) );
```
Comment (roborourke) [inline redirect.php]: Generally prefer to avoid long lines - can you move the `apply_filters()` call to a line above and assign it to a var. Can also document the filter then.

One other thing - should we validate the redirect code? Will it always be `301` or `302`? If it's binary why not have the filter return a simple `true` or `false` and call it `mercator.redirect.permanent`. Can be used like:

```php
add_filter( 'mercator.redirect.permanent', '__return_false' );
```

File: redirect.php [hunk 3]
```diff
@@ -81,8 +82,14 @@ function handle_redirect() {
 		return;
 	}
 
+	// If current domain and domain mapping are the same, exit early.
+	$domain = $mapping->get_site()->domain;
+	if ( $domain == $_SERVER['HTTP_HOST'] ) {
```
Comment (roborourke) [inline redirect.php]: Strict comparison

File: README.md [hunk 4]
```diff
@@ -55,6 +55,9 @@ Defaults to `false`
 add_filter( 'mercator.redirect.legacy.enabled', '__return_true' );
 ```
 
+**mercator.redirect.status.code**
+
+Defaults to 301
```
Comment (roborourke) [inline README.md:60]: Can you add a simple example too? Depending on any changes based on my feedback below that is.

**Review by roborourke — CHANGES_REQUESTED** [review]
Thanks very much for this :)

Few code styles things that need changing and some discussion around the status code filter. I think it could be simplified if it's a binary choice.

Let me know what you think :)

**Comment by spacedmonkey** [comment]
Feedback complete

**Review by roborourke — APPROVED** [review]
